language: php
php:
  - "5.3"
  - "5.4"

before_install:
  - composer install --dev --no-interaction --prefer-source
  - phpenv rehash

script:
  - mkdir -p build/logs/coverage
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
